<?php

/**
 * @file
 * Primary module hooks for foia_annual_data_report module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\AlertCommand;
use Drupal\node\Entity\Node;
use Drupal\node\NodeInterface;
use Drupal\Core\Url;
use Drupal\Core\Ajax\RedirectCommand;

/**
 * Implements hook_form_form_id_alter().
 */
function foia_annual_data_report_form_node_annual_foia_report_data_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  foia_annual_data_report_ajax_existing_node($form, $form_state, $form_id);
}

/**
 * Implements hook_form_form_id_alter().
 */
function foia_annual_data_report_form_node_annual_foia_report_data_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  foia_annual_data_report_ajax_new_node($form, $form_state, $form_id);
}

/**
 * Helper function to add ajax to update the component when the agency changes.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function foia_annual_data_report_ajax_new_node(&$form, FormStateInterface
 $form_state, $form_id) {

  $form['field_agency']['widget'][0]['target_id']['#ajax'] = [
    'callback' => 'foia_annual_data_report_create_node',
    'event' => 'change',
    'progress' => [
      'type' => 'throbber',
      'message' => 'Please Wait...',
    ],
  ];

}

/**
 * Helper function to add ajax to update the component when the agency changes.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function foia_annual_data_report_ajax_existing_node(&$form, FormStateInterface
 $form_state, $form_id) {

  $form['field_agency']['widget'][0]['target_id']['#ajax'] = [
    'callback' => 'foia_annual_data_report_refresh',
    'event' => 'change',
    'progress' => [
      'type' => 'throbber',
      'message' => 'Please Wait...',
    ],
  ];

}

/**
 * Do all the magic to get the component list and update the Component options.
 */
function foia_annual_data_report_create_node($form, FormStateInterface
 $form_state) {

  $is_node = \Drupal::routeMatch()->getParameter('node');
  $response = new AjaxResponse();
  $currentURL = Url::fromRoute('<current>');

  if ($is_node instanceof NodeInterface) {
    $node = Node::load($is_node->nid->value);
    ($node->title->value == '') ? $node->title->value = 'Annual FOIA Report' :
      '';
    $node->set('field_agency', $form['field_agency']['value']);
    $node->save();
  }
  $response->addCommand(new RedirectCommand($currentURL->toString()));
  return $response;
}

/**
 * Do all the magic to get the component list and update the Component options.
 */
function foia_annual_data_report_refresh($form, FormStateInterface
 $form_state) {

  $node = \Drupal::routeMatch()->getParameter('node');
  $response = new AjaxResponse();
  $currentURL = Url::fromRoute('<current>');

  if ($node instanceof NodeInterface) {
    $nid = $node->id();
    $node = Node::load($nid);
    $node->set('field_agency', $form_state->getValue('field_agency'));
    $node->save();
    $response->addCommand(new RedirectCommand($currentURL->toString()));
    $response->addCommand(new AlertCommand("Please wait while the page refreshes"));
  }

  return $response;
}
